IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_LoginInfo')
	DROP TABLE T_LoginInfo;
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_UserRole')
	DROP TABLE T_UserRole;
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_User')
	DROP TABLE T_User;
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_RoleFunc')
	DROP TABLE T_RoleFunc;
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_RoleMenu')
	DROP TABLE T_RoleMenu;
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_MenuFunc')
	DROP TABLE T_MenuFunc;
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_Menu')
	DROP TABLE T_Menu;
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_Role')
	DROP TABLE T_Role;
	

/*
 * 角色
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_Role')
	DROP TABLE T_Role;
CREATE TABLE T_Role(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Name NVARCHAR(50) NOT NULL Unique,
	Description NVARCHAR(100),
	Enable BIT default(1),
	CreateUser NVARCHAR(50),
	CreateTime DATETIME DEFAULT(GETDATE()),	
	UpdateUser NVARCHAR(50),
	UpdateTime DATETIME DEFAULT(GETDATE())
)

/*
 * 用户
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_User')
	DROP TABLE T_User;
CREATE TABLE T_User(
	Account NVARCHAR(50) PRIMARY KEY,
	PWD NVARCHAR(100) NOT NULL,
	UserName NVARCHAR(50) NOT NULL,
	Park NVARCHAR(500),
	Phone NVARCHAR(11),
	Email NVARCHAR(100),
	Addr NVARCHAR(200),
	CreateDate DATETIME DEFAULT(GETDATE()),
	Enable BIT DEFAULT(1),
	CreateUser NVARCHAR(50),
	CreateTime DATETIME DEFAULT(GETDATE()),	
	UpdateUser NVARCHAR(50),
	UpdateTime DATETIME DEFAULT(GETDATE())
)
/*
 * 菜单
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_Menu')
	DROP TABLE T_Menu;
CREATE TABLE T_Menu(
	ID NVARCHAR(50) PRIMARY KEY,
	PID NVARCHAR(50),
	Name NVARCHAR(50),
	Path NVARCHAR(200),
	OrderNum INT,
	Level INT,
	Class NVARCHAR(20)
);
--select *from T_Menu;

/*
 * 菜单功能
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_MenuFunc')
	DROP TABLE T_MenuFunc;
CREATE TABLE T_MenuFunc(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	MenuID NVARCHAR(50) NOT NULL CONSTRAINT FK_MF_M REFERENCES T_MENU(ID),
	Code NVARCHAR(30) NOT NULL,
	Name NVARCHAR(50) NOT NULL
)

/*
 * 菜单权限
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_RoleMenu')
	DROP TABLE T_RoleMenu;
CREATE TABLE T_RoleMenu(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	RoleID INT NOT NULL CONSTRAINT FK_RM_Role REFERENCES T_Role(ID),
	MenuID NVARCHAR(50)NOT NULL CONSTRAINT FK_RM_Menu REFERENCES T_Menu(ID),
)

/*
 * 用户角色
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_UserRole')
	DROP TABLE T_UserRole;
CREATE TABLE T_UserRole(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	UserID NVARCHAR(50) NOT NULL CONSTRAINT FK_UR_User REFERENCES T_User(Account),
	RoleID INT NOT NULL CONSTRAINT FK_UR_Role REFERENCES T_Role(ID)
	
)
--select * from T_UserRole;

/*
 * 功能权限
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_RoleFunc')
	DROP TABLE T_RoleFunc;
CREATE TABLE T_RoleFunc(
	ID INT IDENTITY(1,1) PRIMARY KEY, 
	RoleID INT NOT NULL CONSTRAINT FK_RMF_Role REFERENCES T_Role(ID),
	FuncID INT NOT NULL CONSTRAINT FK_RMF_MF REFERENCES T_MenuFunc(ID),
)
/*
 * 登录
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_LoginInfo')
	DROP TABLE T_LoginInfo;
CREATE TABLE T_LoginInfo(
	ID NVARCHAR(50) PRIMARY KEY,
	UserID NVARCHAR(50) CONSTRAINT FK_Login_MF REFERENCES T_User(Account),
	FailTime DateTime	
)

