
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DorllyResEntities : DbContext
    {
        public DorllyResEntities()
            : base("name=DorllyResEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Menu> T_Menu { get; set; }
        public virtual DbSet<T_Permission> T_Permission { get; set; }
        public virtual DbSet<T_Role> T_Role { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<T_RType> T_RType { get; set; }
        public virtual DbSet<T_RGroup> T_RGroup { get; set; }
        public virtual DbSet<T_Resource> T_Resource { get; set; }
        public virtual DbSet<T_RPrice> T_RPrice { get; set; }
        public virtual DbSet<T_SProvider> T_SProvider { get; set; }
        public virtual DbSet<T_Unit> T_Unit { get; set; }
        public virtual DbSet<T_Building> T_Building { get; set; }
        public virtual DbSet<T_City> T_City { get; set; }
        public virtual DbSet<T_Floor> T_Floor { get; set; }
        public virtual DbSet<T_Park> T_Park { get; set; }
        public virtual DbSet<T_Region> T_Region { get; set; }
        public virtual DbSet<T_Stage> T_Stage { get; set; }
        public virtual DbSet<T_RImage> T_RImage { get; set; }
    }
}
