
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DorllyResEntities : DbContext
    {
        public DorllyResEntities()
            : base("name=DorllyResEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Menu> T_Menu { get; set; }
        public virtual DbSet<T_Permission> T_Permission { get; set; }
        public virtual DbSet<T_Role> T_Role { get; set; }
        public virtual DbSet<T_User> T_User { get; set; }
        public virtual DbSet<T_RType> T_RType { get; set; }
        public virtual DbSet<T_RGroup> T_RGroup { get; set; }
        public virtual DbSet<T_Resource> T_Resource { get; set; }
        public virtual DbSet<T_RPrice> T_RPrice { get; set; }
        public virtual DbSet<T_SProvider> T_SProvider { get; set; }
        public virtual DbSet<T_Unit> T_Unit { get; set; }
        public virtual DbSet<T_Building> T_Building { get; set; }
        public virtual DbSet<T_City> T_City { get; set; }
        public virtual DbSet<T_Floor> T_Floor { get; set; }
        public virtual DbSet<T_Park> T_Park { get; set; }
        public virtual DbSet<T_Region> T_Region { get; set; }
        public virtual DbSet<T_Stage> T_Stage { get; set; }
        public virtual DbSet<T_RImage> T_RImage { get; set; }
        public virtual DbSet<T_StandardPrice> T_StandardPrice { get; set; }
        public virtual DbSet<V_ResOther> V_ResOther { get; set; }
        public virtual DbSet<V_ResRoom> V_ResRoom { get; set; }
    
        public virtual int SP_ResSearch(Nullable<int> model, string floorCode, string buildingCode, string stageCode, string parkCode, string regionCode, string cityCode)
        {
            var modelParameter = model.HasValue ?
                new ObjectParameter("Model", model) :
                new ObjectParameter("Model", typeof(int));
    
            var floorCodeParameter = floorCode != null ?
                new ObjectParameter("FloorCode", floorCode) :
                new ObjectParameter("FloorCode", typeof(string));
    
            var buildingCodeParameter = buildingCode != null ?
                new ObjectParameter("BuildingCode", buildingCode) :
                new ObjectParameter("BuildingCode", typeof(string));
    
            var stageCodeParameter = stageCode != null ?
                new ObjectParameter("StageCode", stageCode) :
                new ObjectParameter("StageCode", typeof(string));
    
            var parkCodeParameter = parkCode != null ?
                new ObjectParameter("ParkCode", parkCode) :
                new ObjectParameter("ParkCode", typeof(string));
    
            var regionCodeParameter = regionCode != null ?
                new ObjectParameter("RegionCode", regionCode) :
                new ObjectParameter("RegionCode", typeof(string));
    
            var cityCodeParameter = cityCode != null ?
                new ObjectParameter("CityCode", cityCode) :
                new ObjectParameter("CityCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("SP_ResSearch", modelParameter, floorCodeParameter, buildingCodeParameter, stageCodeParameter, parkCodeParameter, regionCodeParameter, cityCodeParameter);
        }
    }
}
