//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mstr_Customer
    {
        public string CustNo { get; set; }
        public string CustName { get; set; }
        public string CustShortName { get; set; }
        public string CustType { get; set; }
        public string Representative { get; set; }
        public string BusinessScope { get; set; }
        public string CustLicenseNo { get; set; }
        public string RepIDCard { get; set; }
        public string CustContact { get; set; }
        public string CustTel { get; set; }
        public string CustContactMobile { get; set; }
        public string CustEmail { get; set; }
        public string CustBankTitle { get; set; }
        public string CustBankAccount { get; set; }
        public string CustBank { get; set; }
        public string CustStatus { get; set; }
        public Nullable<System.DateTime> CustCreateDate { get; set; }
        public string CustCreator { get; set; }
        public Nullable<bool> IsExternal { get; set; }
    }
}
