//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cubicle
    {
        public string CubicleCode { get; set; }
        public string CubicleName { get; set; }
        public string RoomCode { get; set; }
        public string GroupCode { get; set; }
        public string CustCode { get; set; }
        public string CubicleAddr { get; set; }
        public Nullable<bool> CubicleEnable { get; set; }
        public Nullable<int> CubicleStatus { get; set; }
        public Nullable<int> CubicleSeat { get; set; }
        public string CubicleContent { get; set; }
        public string RentRangeSeat { get; set; }
        public string RentBeginSeat { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
    }
}
