//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Cust
    {
        public int ID { get; set; }
        public string CustNo { get; set; }
        public string CustName { get; set; }
        public string CustShortName { get; set; }
        public string CustType { get; set; }
        public string CustMail { get; set; }
        public string CustTel { get; set; }
        public string CustAddr { get; set; }
        public string Remark { get; set; }
    }
}
