//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Menu()
        {
            this.T_MenuFunc = new HashSet<T_MenuFunc>();
            this.T_RoleMenu = new HashSet<T_RoleMenu>();
        }
    
        public string ID { get; set; }
        public string PID { get; set; }
        public string Name { get; set; }
        public string Path { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public Nullable<int> Level { get; set; }
        public string Class { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_MenuFunc> T_MenuFunc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_RoleMenu> T_RoleMenu { get; set; }
    }
}
