//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Menu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Menu()
        {
            this.T_Permission = new HashSet<T_Permission>();
        }
    
        public int MenuID { get; set; }
        public Nullable<int> MenuPID { get; set; }
        public string MenuName { get; set; }
        public string MenuPath { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<int> OrderNum { get; set; }
        public string ClassName { get; set; }
        public string FuncCode { get; set; }
        public string FuncName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Permission> T_Permission { get; set; }
    }
}
