//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_MeetingRoom
    {
        public string MRCode { get; set; }
        public string MRName { get; set; }
        public string ParkCode { get; set; }
        public string GroupCode { get; set; }
        public string CustCode { get; set; }
        public string MRAddr { get; set; }
        public Nullable<bool> MREnable { get; set; }
        public Nullable<int> MRStatus { get; set; }
        public Nullable<int> MRSeat { get; set; }
        public Nullable<decimal> MRArea { get; set; }
        public Nullable<decimal> MRDeposit { get; set; }
        public string MRContent { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
    }
}
