//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Order
    {
        public string ID { get; set; }
        public string ResourceID { get; set; }
        public string City { get; set; }
        public string CustName { get; set; }
        public string CustPhone { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public Nullable<int> Status { get; set; }
        public string AuthUser { get; set; }
        public string AuthMark { get; set; }
    
        public virtual T_Resource T_Resource { get; set; }
    }
}
