//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Park
    {
        public int ID { get; set; }
        public string ParkCode { get; set; }
        public string RegionCode { get; set; }
        public string ParkName { get; set; }
        public string ParkShortName { get; set; }
        public string Addr { get; set; }
        public string ContactName { get; set; }
        public string ContactPhone { get; set; }
        public string ContactMobile { get; set; }
        public string ContactEmail { get; set; }
        public string ContactAddr { get; set; }
        public string ContactMark { get; set; }
        public string GisX { get; set; }
        public string GisY { get; set; }
    }
}
