//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_PageFoot
    {
        public int Position { get; set; }
        public string CityID { get; set; }
        public string CSEmail { get; set; }
        public string CSPhone { get; set; }
        public string CSQQ { get; set; }
        public string CompanyEmail { get; set; }
        public string BusinessPhone { get; set; }
        public string ContactPhone { get; set; }
        public string ContactAddr { get; set; }
        public string Content { get; set; }
        public string QRCode1 { get; set; }
        public string QRCode2 { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
