//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Resource
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string ParkID { get; set; }
        public string ShortAddr { get; set; }
        public string FullAddr { get; set; }
        public string SProviderID { get; set; }
        public Nullable<int> RTypeID { get; set; }
        public Nullable<int> RGroupID { get; set; }
        public Nullable<decimal> OriginalArea { get; set; }
        public Nullable<decimal> RentArea { get; set; }
        public Nullable<decimal> LimitRentArea { get; set; }
        public Nullable<decimal> RentOutArea { get; set; }
        public Nullable<int> OriginalNum { get; set; }
        public Nullable<int> RentNum { get; set; }
        public Nullable<int> LimitRentNum { get; set; }
        public Nullable<int> RentOutNum { get; set; }
        public Nullable<int> PersonNum { get; set; }
        public string Size { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Position { get; set; }
        public string Detail { get; set; }
        public string Matching { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string Rmark { get; set; }
        public string FloorID { get; set; }
    
        public virtual T_RType T_RType { get; set; }
    }
}
