//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ResourceGroup
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public int ResourceKindID { get; set; }
        public string ParkID { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    
        public virtual T_ResourceKind T_ResourceKind { get; set; }
    }
}
