//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ResourceStatus
    {
        public int ID { get; set; }
        public string RID { get; set; }
        public string BSID { get; set; }
        public Nullable<int> SYSID { get; set; }
        public Nullable<System.DateTime> BegTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string CustFName { get; set; }
        public string CustSName { get; set; }
        public string CustTel { get; set; }
        public string BSType { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string Remark { get; set; }
        public string UpUser { get; set; }
        public Nullable<System.DateTime> UpTime { get; set; }
    }
}
