//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_ResourcePrice
    {
        public int ID { get; set; }
        public string ResourceID { get; set; }
        public Nullable<bool> YearEnable { get; set; }
        public Nullable<decimal> YearInPrice { get; set; }
        public Nullable<decimal> YearOutPrice { get; set; }
        public Nullable<bool> QuaterEnable { get; set; }
        public Nullable<decimal> QuaterInPrcie { get; set; }
        public Nullable<decimal> QuaterOutPrice { get; set; }
        public Nullable<bool> MonthEnable { get; set; }
        public Nullable<decimal> MonthInPrice { get; set; }
        public Nullable<decimal> MonthOutPrice { get; set; }
        public Nullable<bool> WeekEnable { get; set; }
        public Nullable<decimal> WeekInPrice { get; set; }
        public Nullable<decimal> WeekOutPrice { get; set; }
        public Nullable<bool> DayEnable { get; set; }
        public Nullable<decimal> DayInPrice { get; set; }
        public Nullable<decimal> DayOutPrice { get; set; }
        public Nullable<bool> HDayEnable { get; set; }
        public Nullable<decimal> HDayInPrice { get; set; }
        public Nullable<decimal> HDayOutPrice { get; set; }
        public Nullable<bool> HourEnable { get; set; }
        public Nullable<decimal> HourInPrice { get; set; }
        public Nullable<decimal> HourOutPrice { get; set; }
        public Nullable<bool> SingleEnable { get; set; }
        public Nullable<decimal> SingleInPrice { get; set; }
        public Nullable<decimal> SingleOutPrice { get; set; }
        public Nullable<decimal> DelayInPrice { get; set; }
        public Nullable<decimal> DelayOutPrice { get; set; }
        public Nullable<bool> MeterEnable { get; set; }
        public Nullable<decimal> MeterMinPrice { get; set; }
        public Nullable<decimal> MeterMaxPrice { get; set; }
        public Nullable<bool> IMonthEnable { get; set; }
        public Nullable<decimal> IMonthMinPrice { get; set; }
        public Nullable<decimal> IMonthMaxPrice { get; set; }
        public Nullable<bool> ISingleEnable { get; set; }
        public Nullable<decimal> ISingleMinPrice { get; set; }
        public Nullable<decimal> ISingleMaxPrice { get; set; }
        public Nullable<bool> OnceEnable { get; set; }
        public Nullable<decimal> OnceMinPrice { get; set; }
        public Nullable<decimal> OnceMaxPrice { get; set; }
        public Nullable<bool> OtherEnable { get; set; }
        public Nullable<decimal> OtherMinPrice { get; set; }
        public Nullable<decimal> OtherMaxPrice { get; set; }
    
        public virtual T_Resource T_Resource { get; set; }
    }
}
