//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RGroup
    {
        public int ID { get; set; }
        public Nullable<int> RTypeID { get; set; }
        public string ParkID { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
        public string RGroupCode { get; set; }
        public string RGroupName { get; set; }
    
        public virtual T_RType T_RType { get; set; }
    }
}
