//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Room
    {
        public string RoomCode { get; set; }
        public string RoomName { get; set; }
        public string FloorCode { get; set; }
        public string GroupCode { get; set; }
        public string CustCode { get; set; }
        public string RoomAddr { get; set; }
        public Nullable<bool> RoomEnable { get; set; }
        public Nullable<int> RoomStatus { get; set; }
        public Nullable<int> RentTypeID { get; set; }
        public Nullable<decimal> RoomArea { get; set; }
        public Nullable<decimal> RentArea { get; set; }
        public string RoomContent { get; set; }
        public string RentRangeArea { get; set; }
        public string RentBeginArea { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
    }
}
