//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_RPrice
    {
        public int ID { get; set; }
        public string PriceName { get; set; }
        public string ResourceCode { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> InPrice { get; set; }
        public Nullable<decimal> OutPrice { get; set; }
        public Nullable<decimal> InDelayPrice { get; set; }
        public Nullable<decimal> OutDelayPrice { get; set; }
        public string UnitName { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string UpdateUser { get; set; }
    }
}
