//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_User
    {
        public int ID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public int RoleID { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public string Addr { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual T_Role T_Role { get; set; }
    }
}
