//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Floor
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string BuildingID { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string FullPosition { get; set; }
        public string BuildingName { get; set; }
        public string StageID { get; set; }
        public string StageName { get; set; }
        public string ParkID { get; set; }
        public string ParkName { get; set; }
        public string RegionID { get; set; }
        public string RegionName { get; set; }
        public string CityID { get; set; }
        public string CityName { get; set; }
    }
}
