//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Func
    {
        public int ID { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string RoleName { get; set; }
        public string MenuName { get; set; }
        public string MenuPath { get; set; }
        public string FuncCode { get; set; }
        public string FuncName { get; set; }
        public string FuncClass { get; set; }
        public string FuncColor { get; set; }
    }
}
