//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Park
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string FullName { get; set; }
        public string RegionID { get; set; }
        public string Addr { get; set; }
        public string GisX { get; set; }
        public string GisY { get; set; }
        public string ContactsName { get; set; }
        public string ContactsPhone { get; set; }
        public string ContactsMobile { get; set; }
        public string ContactsEmail { get; set; }
        public string ContactsAddr { get; set; }
        public string ReMark { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string FullPosition { get; set; }
        public string RegionName { get; set; }
        public string CityID { get; set; }
        public string CityName { get; set; }
    }
}
