//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_Public
    {
        public string ID { get; set; }
        public string ResourceID { get; set; }
        public Nullable<int> Level { get; set; }
        public Nullable<System.DateTime> BeginTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<bool> AZWEnable { get; set; }
        public Nullable<bool> AZGJEnable { get; set; }
        public Nullable<bool> ZYPTEnable { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string ResourceName { get; set; }
        public string Loc1 { get; set; }
        public string Loc1Name { get; set; }
        public Nullable<int> ResourceKindID { get; set; }
        public string ResourceKindName { get; set; }
        public string GroupID { get; set; }
        public string GroupName { get; set; }
    }
}
