//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ResRoom
    {
        public string RID { get; set; }
        public string RNAME { get; set; }
        public string FCODE { get; set; }
        public string FNAME { get; set; }
        public string BCODE { get; set; }
        public string BNAME { get; set; }
        public string SCODE { get; set; }
        public string SNAME { get; set; }
        public string PCODE { get; set; }
        public string PNAME { get; set; }
        public string GCODE { get; set; }
        public string GNAME { get; set; }
        public string CCODE { get; set; }
        public string CNAME { get; set; }
    }
}
