//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_ResourceStatus
    {
        public int ID { get; set; }
        public int SysID { get; set; }
        public string ResourceID { get; set; }
        public string BusinessID { get; set; }
        public int BusinessType { get; set; }
        public System.DateTime RentBeginTime { get; set; }
        public System.DateTime RentEndTime { get; set; }
        public Nullable<int> RentType { get; set; }
        public Nullable<decimal> RentArea { get; set; }
        public string CustLongName { get; set; }
        public string CustShortName { get; set; }
        public string CustTel { get; set; }
        public string ReserveDept { get; set; }
        public string ReserveName { get; set; }
        public string Remark { get; set; }
        public int Status { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string ResourceName { get; set; }
        public string Loc1 { get; set; }
        public string Loc1Name { get; set; }
        public string Loc2 { get; set; }
        public string Loc2Name { get; set; }
        public string Loc3 { get; set; }
        public string Loc3Name { get; set; }
        public string Loc4 { get; set; }
        public string Loc4Name { get; set; }
        public string Loc5 { get; set; }
        public string Loc5Name { get; set; }
        public string LocText { get; set; }
        public string GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ResourceKindID { get; set; }
        public string ResourceKindName { get; set; }
        public string ResourceTypeID { get; set; }
        public string ResourceTypeName { get; set; }
        public Nullable<bool> ResourceEnable { get; set; }
    }
}
