//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RS_Info
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string Loc1 { get; set; }
        public string Loc2 { get; set; }
        public string Loc3 { get; set; }
        public string Loc4 { get; set; }
        public string Loc5 { get; set; }
        public string ParkID { get; set; }
        public string ParentID { get; set; }
        public string GroupID { get; set; }
        public int ResourceKindID { get; set; }
        public string ResourceTypeID { get; set; }
        public Nullable<int> RSID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> RentArea { get; set; }
        public Nullable<decimal> StartArea { get; set; }
        public string RangeArea { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> RentNum { get; set; }
        public Nullable<int> StartNum { get; set; }
        public string RangeNum { get; set; }
        public string Size { get; set; }
        public string RentSize { get; set; }
        public string StartSize { get; set; }
        public string RangeSize { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Content { get; set; }
        public string Remark { get; set; }
        public string Location { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
        public string ResourceKindName { get; set; }
        public string ResourceTypeName { get; set; }
        public string GroupName { get; set; }
        public string Loc1Name { get; set; }
        public string Loc2Name { get; set; }
        public string Loc3Name { get; set; }
        public string Loc4Name { get; set; }
        public string Loc5Name { get; set; }
        public string LocText { get; set; }
        public Nullable<System.DateTime> BegTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public string CustFName { get; set; }
        public string CustSName { get; set; }
        public string CustTel { get; set; }
        public Nullable<bool> YearEnable { get; set; }
        public Nullable<decimal> YearInPrice { get; set; }
        public Nullable<decimal> YearOutPrice { get; set; }
        public Nullable<bool> QuaterEnable { get; set; }
        public Nullable<decimal> QuaterInPrcie { get; set; }
        public Nullable<decimal> QuaterOutPrice { get; set; }
        public Nullable<bool> MonthEnable { get; set; }
        public Nullable<decimal> MonthInPrice { get; set; }
        public Nullable<decimal> MonthOutPrice { get; set; }
        public Nullable<bool> WeekEnable { get; set; }
        public Nullable<decimal> WeekInPrice { get; set; }
        public Nullable<decimal> WeekOutPrice { get; set; }
        public Nullable<bool> DayEnable { get; set; }
        public Nullable<decimal> DayInPrice { get; set; }
        public Nullable<decimal> DayOutPrice { get; set; }
        public Nullable<bool> HDayEnable { get; set; }
        public Nullable<decimal> HDayInPrice { get; set; }
        public Nullable<decimal> HDayOutPrice { get; set; }
        public Nullable<bool> HourEnable { get; set; }
        public Nullable<decimal> HourInPrice { get; set; }
        public Nullable<decimal> HourOutPrice { get; set; }
        public Nullable<bool> SingleEnable { get; set; }
        public Nullable<decimal> SingleInPrice { get; set; }
        public Nullable<decimal> SingleOutPrice { get; set; }
        public Nullable<bool> DelayEnable { get; set; }
        public Nullable<decimal> DelayInPrice { get; set; }
        public Nullable<decimal> DelayOutPrice { get; set; }
        public Nullable<bool> MeterEnable { get; set; }
        public Nullable<decimal> MeterMinPrice { get; set; }
        public Nullable<decimal> MeterMaxPrice { get; set; }
        public Nullable<bool> IMonthEnable { get; set; }
        public Nullable<decimal> IMonthMinPrice { get; set; }
        public Nullable<decimal> IMonthMaxPrice { get; set; }
        public Nullable<bool> ISingleEnable { get; set; }
        public Nullable<decimal> ISingleMinPrice { get; set; }
        public Nullable<decimal> ISingleMaxPrice { get; set; }
        public Nullable<bool> OnceEnable { get; set; }
        public Nullable<decimal> OnceMinPrice { get; set; }
        public Nullable<decimal> OnceMaxPrice { get; set; }
        public Nullable<bool> OtherEnable { get; set; }
        public Nullable<decimal> OtherMinPrice { get; set; }
        public Nullable<decimal> OtherMaxPrice { get; set; }
    }
}
