//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_RSS_Info
    {
        public int ID { get; set; }
        public Nullable<int> SysID { get; set; }
        public string RID { get; set; }
        public string BSID { get; set; }
        public Nullable<int> BSType { get; set; }
        public Nullable<System.DateTime> BegTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
        public Nullable<int> EndType { get; set; }
        public Nullable<System.DateTime> RealEndTime { get; set; }
        public string Company { get; set; }
        public string ContactName { get; set; }
        public string ContactTel { get; set; }
        public string ReserveDept { get; set; }
        public string ReserveName { get; set; }
        public string Remark { get; set; }
        public Nullable<bool> Enable { get; set; }
        public string UpUser { get; set; }
        public Nullable<System.DateTime> UpTime { get; set; }
        public string RName { get; set; }
        public string Loc1 { get; set; }
        public string Loc1Name { get; set; }
        public string GroupID { get; set; }
        public string GroupName { get; set; }
        public Nullable<int> ResourceKindID { get; set; }
        public string ResourceKindName { get; set; }
        public string ResourceTypeID { get; set; }
        public string ResourceTypeName { get; set; }
        public Nullable<bool> REnable { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<decimal> MaxPrice { get; set; }
        public Nullable<decimal> MinPrice { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> RentArea { get; set; }
        public Nullable<decimal> StartArea { get; set; }
        public string RangeArea { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> RentNum { get; set; }
        public Nullable<int> StartNum { get; set; }
        public string RangeNum { get; set; }
        public string Size { get; set; }
        public string RentSize { get; set; }
        public string StartSize { get; set; }
        public string RangeSize { get; set; }
        public Nullable<decimal> Deposit { get; set; }
        public string Content { get; set; }
        public string Location { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
    }
}
