//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_SRM
    {
        public string ID { get; set; }
        public string Name { get; set; }
        public string ParkID { get; set; }
        public string ParkName { get; set; }
        public string StageID { get; set; }
        public string StageName { get; set; }
        public string BuildingID { get; set; }
        public string BuildingName { get; set; }
        public string FloorID { get; set; }
        public string FloorName { get; set; }
        public string GroupID { get; set; }
        public string GroupName { get; set; }
        public string CustID { get; set; }
        public string CustName { get; set; }
        public int ResourceKindID { get; set; }
        public string ResourceKindName { get; set; }
        public string ResourceTypeID { get; set; }
        public string ResourceTypeName { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<bool> Enable { get; set; }
        public Nullable<System.DateTime> RentBeginTime { get; set; }
        public Nullable<System.DateTime> RentEndTime { get; set; }
        public Nullable<decimal> Area { get; set; }
        public Nullable<decimal> RentArea { get; set; }
        public string CustPhone { get; set; }
    }
}
