//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resource.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class V_WYContract
    {
        public string SYSID { get; set; }
        public string ResourceID { get; set; }
        public string BusinessID { get; set; }
        public string BusinessType { get; set; }
        public Nullable<System.DateTime> RentBeginTime { get; set; }
        public Nullable<System.DateTime> RentEndTime { get; set; }
        public Nullable<decimal> RentArea { get; set; }
        public string CustLongName { get; set; }
        public string CustShortName { get; set; }
        public string CustTel { get; set; }
        public string ReserveDept { get; set; }
        public string ReserveName { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public string UpdateUser { get; set; }
        public Nullable<System.DateTime> UpdateTime { get; set; }
    }
}
