/*
 * 角色表
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_Role')
	DROP TABLE T_Role;
CREATE TABLE T_Role(
	ID INT IDENTITY(10001,1) PRIMARY KEY,		--角色编号
	RoleName NVARCHAR(50) NOT NULL,				--角色名称
	RoleDesc NVARCHAR(100)						--角色描述
)
insert into T_Role values('Admin','超级管理员');
SELECT * FROM T_Role;
/*
 * 用户表
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_User')
	DROP TABLE T_User;
CREATE TABLE T_User(
	ID INT IDENTITY(20001,1) PRIMARY KEY,
	UserName NVARCHAR(50) NOT NULL,
	Password NVARCHAR(100) NOT NULL,
	NickName NVARCHAR(50),
	RoleID INT NOT NULL CONSTRAINT FK_ROLE_User REFERENCES T_ROLE(ID),
	Phone NVARCHAR(11),
	Email NVARCHAR(100),
	Addr NVARCHAR(200),
	CreateDate DATETIME DEFAULT(GETDATE()),
	Status BIT
)
INSERT INTO T_User VALUES('LUOWENYU','123456','FUCKY',10001,'13168790599','LUOWENYUYU@QQ.COM','广东深圳',DEFAULT,1);
SELECT *FROM T_User;
/*
 * 菜单表
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_Menu')
	DROP TABLE T_Menu;
CREATE TABLE T_Menu(
	ID INT IDENTITY(30001,1) PRIMARY KEY,
	PID INT,
	MenuName NVARCHAR(50),
	MenuPath NVARCHAR(200),
	MenuLevel INT,
	OrderNum INT,
	ClassName NVARCHAR(20),
	FuncCode NVARCHAR(500),
	FuncName NVARCHAR(500)
)

/*
 * 权限表
 */
IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_Permission')
	DROP TABLE T_Permission;
CREATE TABLE T_Permission(
	ID INT IDENTITY(40001,1) PRIMARY KEY,
	RoleID INT NOT NULL ,
	MenuID INT NOT NULL,
	FuncCode NVARCHAR(500)
)
