/*
 * 资源类别表
 */
 IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_RType')
	DROP TABLE T_RType;
CREATE TABLE T_RType(
	ID INT IDENTITY(1,1) PRIMARY KEY,	--类别编号
	Name NVARCHAR(30) NOT NULL			--类别名称
)
INSERT INTO T_RType VALUES('房屋');
INSERT INTO T_RType VALUES('工位');
INSERT INTO T_RType VALUES('会议室');
INSERT INTO T_RType VALUES('广告位');
SELECT * FROM T_RType;