/*
 * 资源分组表
 */
 IF EXISTS(SELECT * FROM DBO.SYSOBJECTS WHERE name='T_RGroup')
	DROP TABLE T_RGroup;
CREATE TABLE T_RGroup(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	RGroupCode NVARCHAR(30),
	RGroupName NVARCHAR(30),
	RTypeID INT,
	ParkID NVARCHAR(30),
	Status BIT,
	UpdateTime DATETIME DEFAULT(GETDATE()),
	UpdateUser NVARCHAR(30)	
)
ALTER TABLE T_RGroup ADD CONSTRAINT FK_RG_RType FOREIGN KEY(RTypeID) REFERENCES T_RType(ID)
ALTER TABLE T_RGroup DROP CONSTRAINT FK_RG_Park;
ALTER TABLE T_RGroup ADD CONSTRAINT FK_RG_Park FOREIGN KEY(ParkID) REFERENCES T_Location(ID)
INSERT INTO T_RGroup VALUES('FZ-WE','测试分组',1,'FTYQ',1,default,'admin');
INSERT INTO T_RGroup VALUES('FZ-WEda','测试分组',2,'FTYQ',1,default,'admin');
select * from T_RGroup;